// AUTO-GENERATED by scripts/gen-settings-registry.mjs — DO NOT EDIT
// Re-generate with: npm run gen:settings

import type { SettingEntry } from './settingsTypes'

export const SETTINGS_REGISTRY: SettingEntry[] = 
[
  {
    "id": "browser.chrome-extension-mode",
    "label": "Chrome Extension Mode",
    "description": "Attach to your running Chrome with all existing logins and sessions. Recommended for macOS.",
    "tab": "browser",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "browser.connection-token",
    "label": "Connection Token",
    "description": "Paste PLAYWRIGHT_MCP_EXTENSION_TOKEN value from the extension popup",
    "tab": "browser",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "channels.owner-slack-member-id",
    "label": "Owner Slack member ID",
    "description": "The one member who can always interact with the bot (KIROCREW_OWNER_ID). Starts with U or W.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.phase-reactions",
    "label": "Phase reactions",
    "description": "Show phase-aware emoji reactions (queued → thinking → coding → done) on messages.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.show-thinking",
    "label": "Show thinking",
    "description": "Post the model's reasoning as a thread reply. Disable to keep responses concise.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.slash-command",
    "label": "Slash command",
    "description": "Trigger word for the Slack slash command (without the leading /).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "chat.auto-add-documents",
    "label": "Auto-Add Documents",
    "description": "Let the agent add documents it reads while working to your knowledge library, so they stay searchable later. It reads them with its own tools under your approval — Kiro Crew fetches nothing itself. Added documents appear in one “Auto-added” source you can remove in a click.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.auto-add-saved-artifacts",
    "label": "Auto-Add Saved Artifacts",
    "description": "Mirror documents you save as artifacts into the library, keep them in sync as you edit, and remove them when you delete the artifact.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.auto-compact-threshold",
    "label": "Auto-Compact Threshold",
    "description": "Context usage % at which auto-compaction triggers. Lower = more frequent compaction, longer sessions",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.auto-ingest-limit-per-scan",
    "label": "Auto-Ingest Limit Per Scan",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.auto-register-project-documents",
    "label": "Auto-Register Project Documents",
    "description": "Register the documents of each project you work in, so its design docs, specs and READMEs become searchable without adding the folder by hand. Documents only — never source code, agent instructions or generated files.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.background-effort",
    "label": "Background Effort",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.background-model",
    "label": "Background Model",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.completion-event-characters",
    "label": "Completion Event Characters",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.completion-event-truncation",
    "label": "Completion Event Truncation",
    "description": "Which part of a subagent's stream to keep when injecting its completion event into the parent session. Head preserves the start (default, matches legacy behavior). Tail preserves the final summary. Both keeps a slice from each end with a marker between them.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.confirm-before-closing-session",
    "label": "Confirm Before Closing Session",
    "description": "Show a confirmation dialog when closing a session",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.content-width",
    "label": "Content Width",
    "description": "Compact is the original view. Comfortable and Full use more screen space.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.default-reasoning-effort",
    "label": "Default Reasoning Effort",
    "description": "How long models think before answering by default. Higher is slower and costs more. Only available on reasoning-capable models (Opus, Sonnet, Fable, GPT-5.x).",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.default-to-autopilot-mode",
    "label": "Default to Autopilot Mode",
    "description": "New sessions start in autopilot mode (plan → approve → execute). You can still toggle individual sessions.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.describe-your-role",
    "label": "Describe your role",
    "description": "Kiro quotes this back to itself when calibrating vocabulary and examples.",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.fallback-model",
    "label": "Fallback Model",
    "description": "Which model new sessions start with when their agent pins none. Set a model per agent under Capabilities → Crews, or pick one inside a session to override it there.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.feature-tips",
    "label": "Feature Tips",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.file-change-chips",
    "label": "File Change Chips",
    "description": "How file diff chips appear below assistant messages",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.folder-suggestions",
    "label": "Folder suggestions",
    "description": "Offer to file a new session into a matching folder once it has a title.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.follow-up-bar-layout",
    "label": "Follow-Up Bar Layout",
    "description": "Multiline wraps suggestions onto multiple rows. Single line keeps them on one horizontally-scrollable row.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.history-expanded",
    "label": "History Expanded",
    "description": "Expand history sidebar by default",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.link-previews",
    "label": "Link Previews",
    "description": "Show a favicon and page title instead of the raw URL. This machine then fetches every link the model outputs, so each linked site sees a request from your IP address.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.mcp-apps-in-side-panel",
    "label": "MCP Apps in Side Panel",
    "description": "Render interactive MCP Apps (such as Excalidraw diagrams) in the right side panel instead of inline in the chat. The panel opens automatically.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.merge-queued-messages",
    "label": "Merge Queued Messages",
    "description": "Combine follow-up messages into a single labeled prompt while the agent is busy",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.pin-the-latest-prompt",
    "label": "Pin the latest prompt",
    "description": "Keep the most recent prompt visible as a sticky banner once it scrolls above the fold.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.prevent-sleep-while-running",
    "label": "Prevent sleep while running",
    "description": "Keep your computer awake while a task is running",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.quick-send",
    "label": "Quick Send",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.response-verbosity",
    "label": "Response Verbosity",
    "description": "How terse the agent's prose is. Ultra-concise writes for an ADHD reader: the answer lands in an opening of at most three sentences, and any detail after it must be scannable bullets rather than prose. Code, commands, and error strings stay verbatim; security warnings and multi-step instructions keep full detail at every level.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.restore-sessions",
    "label": "Restore Sessions",
    "description": "Re-open recently active sessions on startup",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.restore-window",
    "label": "Restore Window",
    "description": "Time window for session restoration",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.send-shortcut",
    "label": "Send shortcut",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.show-context-percentage",
    "label": "Show Context Percentage",
    "description": "Display usage percentage next to the context progress bar",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-thinking-inline",
    "label": "Show Thinking Inline",
    "description": "Show intermediate reasoning text between tool calls instead of collapsing everything",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-timestamps",
    "label": "Show Timestamps",
    "description": "Display time on each message",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.simplified-tool-call-names",
    "label": "Simplified Tool Call Names",
    "description": "When enabled, inline tool pills show simplified tool use purpose instead of the exact command being run",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.soft-stop-budget-seconds",
    "label": "Soft-stop budget (seconds)",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.split-view-session-grid",
    "label": "Split View (Session Grid)",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.subagent-effort",
    "label": "Subagent Effort",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.subagent-model",
    "label": "Subagent Model",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.tail-only-fork",
    "label": "Tail-only Fork",
    "description": "Fork keeps only the messages after the chosen point instead of those up to it.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.technical-comfort",
    "label": "Technical Comfort",
    "description": "Sets how deep explanations go — plain language vs. full technical detail",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.text-streaming-style",
    "label": "Text Streaming Style",
    "description": "Immediate mode shows raw chunks as they arrive. Smooth mode buffers and fades text in at a steady pace.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.widget-density",
    "label": "Widget Density",
    "description": "How aggressively the agent uses inline widgets for visual content",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.your-role",
    "label": "Your Role",
    "description": "Kiro matches vocabulary and examples to your professional background",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "computer-use.attach-screenshots",
    "label": "Attach screenshots",
    "description": "Also capture the target window and pass its file path. The accessibility tree stays the primary channel; windows containing a password field are never captured.",
    "tab": "computer-use",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "computer-use.enable-computer-use",
    "label": "Enable computer use",
    "description": "Let the agent read desktop app windows through accessibility and act on their controls. Off until you turn it on here — an agent cannot enable it.",
    "tab": "computer-use",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "computer-use.max-tree-nodes",
    "label": "Max tree nodes",
    "description": "How many controls one window reading returns. A window with more than this gets truncated, and the agent is told so. Raise it for dense apps (a spreadsheet, an IDE); lower it to spend fewer tokens per reading.",
    "tab": "computer-use",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "computer-use.screenshot-width",
    "label": "Screenshot width",
    "description": "Longest edge of the screenshot, in pixels. Smaller is cheaper and faster to read; larger keeps small text legible if the agent has to fall back to the image.",
    "tab": "computer-use",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "computer-use.show-cursor-motion",
    "label": "Show cursor motion",
    "description": "Draw a cursor that glides to each target and pulses when it clicks, so you can follow along on screen. Purely visual — it changes nothing about what the agent is allowed to do, and it only appears for clicks that move the real pointer.",
    "tab": "computer-use",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.developer-mode",
    "label": "Developer Mode",
    "description": "Show Developer page in sidebar with Logs, System metrics, and Memory internals",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "display.display-mode",
    "label": "Display Mode",
    "description": "How the session color is applied to the row.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.font",
    "label": "Font",
    "description": "Font for the built-in terminal. Enter a monospace font installed on your computer — use a Nerd Font to render Powerline and prompt-theme glyphs.",
    "tab": "display",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "display.font-family",
    "label": "Font Family",
    "description": "UI font family for the dashboard",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.font-size",
    "label": "Font size",
    "description": "Text size in the built-in terminal, measured in pixels.",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "display.highlight-recent-sessions",
    "label": "Highlight recent sessions",
    "description": "Highlight the N most-recently-active sessions with a graded accent stripe (0 = off). Saved to your Kiro Crew config.",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "display.intensity",
    "label": "Intensity",
    "description": "How visible the color tint is on sidebar rows.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.interface",
    "label": "Interface",
    "description": "Chat bubbles or CLI-style line-by-line output",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.language",
    "label": "Language",
    "description": "Language for the dashboard interface.",
    "tab": "display",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "display.mode",
    "label": "Mode",
    "description": "Light or dark appearance for the dashboard",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.palette",
    "label": "Palette",
    "description": "Choose a color palette for your sidebar sessions.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.theme",
    "label": "Theme",
    "description": "Select a theme for the dashboard",
    "tab": "display",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "display.zoom-level",
    "label": "Zoom Level",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "notifications.play-sound-on-new-notifications",
    "label": "Play sound on new notifications",
    "tab": "notifications",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "security.trust-every-third-party-app",
    "label": "Trust every third-party app",
    "description": "Off by default. When on, every third-party app you install can run its own code straight away, without asking you first.",
    "tab": "security",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "skills.auto-generate-skills-from-sessions",
    "label": "Auto-generate skills from sessions",
    "description": "Analyze each completed session and draft a reusable SKILL.md when a non-trivial multi-step procedure is detected. Off by default. Drafts are staged to the pending queue on the Skills tab for review — nothing goes live without your approval (see below).",
    "tab": "skills",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "skills.require-approval-before-generated-skills-go-live",
    "label": "Require approval before generated skills go live",
    "description": "Keep every auto-generated candidate in the pending queue until you approve it. Turning this off lets prose-only skills publish automatically; skills that bundle scripts always require approval regardless.",
    "tab": "skills",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.auto-speak-responses",
    "label": "Auto-speak Responses",
    "description": "Speak every assistant reply automatically",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.auto-submit-when-i-finish-speaking",
    "label": "Auto-submit when I finish speaking",
    "description": "Use a fast model to detect when you've finished a complete request and send it automatically. Streaming providers only.",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.aws-profile-amazon-polly",
    "label": "AWS Profile (Amazon Polly)",
    "description": "AWS credentials profile for Amazon Polly",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-profile-transcribe",
    "label": "AWS Profile (Transcribe)",
    "description": "AWS credentials profile for Transcribe (blank = default chain)",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-region-amazon-polly",
    "label": "AWS Region (Amazon Polly)",
    "description": "AWS region for Amazon Polly API",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-region-transcribe",
    "label": "AWS Region (Transcribe)",
    "description": "AWS region for Transcribe",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.dictation-panel",
    "label": "Dictation panel",
    "description": "Show an animated panel while recording instead of the thin status bar. Falls back to the bar when the browser lacks WebGL2 or your system requests reduced motion.",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.enabled",
    "label": "Enabled",
    "description": "Transcribe voice into the message box when you click the mic",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.engine",
    "label": "Engine",
    "description": "Amazon Polly engine type",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.language",
    "label": "Language",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.microphone",
    "label": "Microphone",
    "description": "Input device used to capture your voice",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.mlx-model",
    "label": "MLX Model",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.model",
    "label": "Model",
    "description": "Larger models are more accurate but slower to run",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.piper-binary",
    "label": "Piper Binary",
    "description": "Path to the piper executable. Leave blank to auto-detect on PATH or ~/piper-venv/bin/piper",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.piper-model",
    "label": "Piper Model",
    "description": "Path to the Piper voice model (.onnx). Required — download from github.com/rhasspy/piper",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.provider",
    "label": "Provider",
    "description": "Whisper, MLX and Apple Speech run locally; Transcribe calls AWS",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.provider-2",
    "label": "Provider",
    "description": "Piper runs locally and offline; Amazon Polly uses AWS credentials + network",
    "tab": "voice",
    "type": "select",
    "occurrence": 2
  },
  {
    "id": "voice.speed",
    "label": "Speed",
    "description": "Speech rate",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.speed-2",
    "label": "Speed",
    "description": "Piper speech speed (length scale)",
    "tab": "voice",
    "type": "select",
    "occurrence": 2
  },
  {
    "id": "voice.streaming",
    "label": "Streaming",
    "description": "Stream live partial transcripts into the input box as you speak. Supported by Transcribe (AWS) and Apple Speech (on-device).",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.voice",
    "label": "Voice",
    "description": "Amazon Polly voice for TTS",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  }
]
